services:
  bbailabs-website:
    image: matthewscott967/bbailabs_website
    networks:
        - bbailabs
    ports:
        - "80:80"
    depends_on:
      - pininfo-api
    build:
      context: AngularSite/
      dockerfile: Dockerfile

  pininfo-api:
    image: matthewscott967/pininfo_api
    networks:
        - bbailabs
    ports:
        - "5000:5000"
    build:
      context: BBAILabsPinInfoAPI/
      dockerfile: Dockerfile

networks:
  bbailabs:
    driver: bridge 
