x-aws-loadbalancer: arn:aws:elasticloadbalancing:us-east-1:020773916720:loadbalancer/net/BBAI-LABS-WEB-LB/72c486ad243568be
services:
  bbailabs-website:
    image: matthewscott967/bbailabs_website

    ports:
        - "80:80"
    depends_on:
      - pininfo-api
    build:
      context: AngularSite/
      dockerfile: Dockerfile

  pininfo-api:
    image: matthewscott967/pininfo_api

    ports:
        - "5000:5000"
    build:
      context: BBAILabsPinInfoAPI/
      dockerfile: Dockerfile
